### ISSUE TITLE
ValueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by aztrock** [brutasse/asyncio-sse#4]
> Traceback (most recent call last):
>  File "/tmp/env/lib/python3.4/site-packages/aiohttp/server.py", line 193, in start
>    yield from handler
>  File "/tmp/env/lib/python3.4/site-packages/sse/protocol.py", line 35, in handle_request
>    handler.validate_sse()
>  File "/tmp/env/lib/python3.4/site-packages/sse/handler.py", line 30, in validate_sse
>    for header, value in self.request.headers:
> VlueError: too many values to unpack (expected 2)

in first example in README

**Comment by SorX14** [comment]
Change line 35 in handler.py to:

`for header, value in self.request.headers.items():`

Adding `.items()` on the end; worked for me

**Comment by aztrock** [comment]
Change in line 30, for header, value in self.request.headers.items():

but another error:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/aiohttp/server.py", line 215, in start
    yield from handler
  File "/usr/local/lib/python3.4/dist-packages/sse/protocol.py", line 42, in handle_request
    response.write_eof()
  File "/usr/local/lib/python3.4/dist-packages/aiohttp/protocol.py", line 715, in write_eof
    return self.transport.drain()
AttributeError: '_SelectorSocketTransport' object has no attribute 'drain'

**Comment by ghost** [comment]
Adding .items() to self.request.headers works fine for me as well
